version: '3.7'

services:

  fidel-dev:
    env_file:
      - .env
    container_name: fidel-dev-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:2222
    environment:
      - CHOKIDAR_USEPOLLING=true