

export const UPDATE_FILTERS = 'UPDATE_FILTERS'

export const FETCHING_INITIAL_DATA = 'FETCHING_INITIAL_DATA'
export const ERROR_FETCHING_INITIAL_DATA = 'ERROR_FETCHING_INITIAL_DATA'
export const DONE_FETCHING_INITIAL_DATA = 'DONE_FETCHING_INITIAL_DATA'

export const FETCHING_MORE_DATA = 'FETCHING_MORE_DATA'
export const ERROR_FETCHING_MORE_DATA = 'ERROR_FETCHING_MORE_DATA'
export const DONE_FETCHING_MORE_DATA = 'DONE_FETCHING_MORE_DATA'

export const UPDATE_HASH_MAP = 'UPDATE_HASH_MAP'
export const FILTER_UPDATE_LOG = 'FILTER_UPDATE_LOG'

export const CLEANUP = 'CLEANUP'

export type ACTION_TYPE =
  | typeof UPDATE_FILTERS
  | typeof FETCHING_INITIAL_DATA
  | typeof ERROR_FETCHING_INITIAL_DATA
  | typeof DONE_FETCHING_INITIAL_DATA
  | typeof FETCHING_MORE_DATA
  | typeof ERROR_FETCHING_MORE_DATA
  | typeof DONE_FETCHING_MORE_DATA
  | typeof UPDATE_HASH_MAP
  | typeof FILTER_UPDATE_LOG
  | typeof CLEANUP

