export const UPDATE_PAGINATION = 'UPDATE_PAGINATION'
export const FETCHING_TRANSACTIONS = 'FETCHING_TRANSACTIONS'
export const ERROR_FETCHING_TRANSACTIONS = 'ERROR_FETCHING_TRANSACTIONS'
export const FETCHED_TRANSACTIONS = ' FETCHED_TRANSACTIONS'

export type ACTION_TYPE =
  | typeof UPDATE_PAGINATION
  | typeof FETCHING_TRANSACTIONS
  | typeof ERROR_FETCHING_TRANSACTIONS
  | typeof FETCHED_TRANSACTIONS
